config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  
  resources :posts
  resources :join_communities, :only => [:show, :create, :destroy]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
  resources :communities do
    resources :join_communities, only: [:index]
  end
  
 resources :users
  

  
  
  get 'community/search'
  
  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  
  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: {maximum: 15}
  VALID_PASSWORED_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  validates :password, presence: true,  uniqueness: true, length: {minimum: 8, maximum: 32 }, format: {with: VALID_PASSWORED_REGEX}
  validates :artist, length: { maximum: 300 }
  validates :description, length: { maximum: 300 }

  mount_uploader :image, ImageUploader
  
  has_secure_password
  
  has_many :communities, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :join_communities
  has_many :join_community_communities, through: :communities, source: 'community'
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  acts_as_followable
  acts_as_follower
  
  enum prefecture: {
   北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
   茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
   新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
   岐阜県:21,静岡県:22,愛知県:23,三重県:24,
   滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
   鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
   徳島県:36,香川県:37,愛媛県:38,高知県:39,
   福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  
  enum age: {
    １:1,２:2,３:3,４:4,５:5,６:6,７:7,８:8,９:9,１０:10,
    １１:11,１２:12,１３:13,１４:14,１５:15,１６:16,１７:17,１８:18,１９:19,２０:20,
    ２１:21,２２:22,２３:23,２４:24,２５:25,２６:26,２７:27,２８:28,２９:29,３０:30,
    ３１:31,３２:32,３３:33,３４:34,３５:35,３６:36,３７:37,３８:38,３９:39,４０:40,
    ４１:41,４２:42,４３:43,４４:44,４５:45,４６:46,４７:47,４８:48,４９:49,５０:50,
    ５１:51,５２:52,５３:53,５４:54,５５:55,５６:56,５７:57,５８:58,５９:59,６０:60,
    ６１:61,６２:62,６３:63,６４:64,６５:65,６６:66,６７:67,６８:68,６９:69,７０:70,
    ７１:71,７２:72,７３:73,７４:74,７５:75,７６:76,７７:77,７８:78,７９:79,８０:80,
    ８１:81,８２:82,８３:83,８４:84,８５:85,８６:86,８７:87,８８:88,８９:89,９０:90,
    ９１:91,９２:92,９３:93,９４:94,９５:95,９６:96,９７:97,９８:98,９９:99,１００:100
  }
  
  enum gender: {
    男性:1,女性:2
  }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id 
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

   def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to root_path, danger: 'そのページにはいけません'
    end
   end
   
   def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(current_user.id), success: '変更しました'
      else 
        flash.now[:danger] = '変更失敗しました'
        render :edit
      end
   end
   
   def follow
     @user = User.find(params[:user_id])
     current_user.follow(@user)
     redirect_to user_path(@user.id)
   end

  def unfollow
    @user = User.find(params[:user_id])
    current_user.stop_following(@user)
    redirect_to user_path(@user.id)
  end
  
  def follow_list
    @user = User.find(params[:user_id])
  end

  def follower_list
    @user = User.find(params[:user_id])
  end
    
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :gender, :age, :artist, :description, :prefecture)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_message.html.erb
<div class="message-btn">
  <% if @isRoom == true %>
    <%= link_to "メッセージ", room_path(@roomId), class: 'follow-message btn btn-hover btn-default' %>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
      <% end %>
      <%= f.submit "メッセージ", class: "follow-message btn btn-default" %>
    <% end %>
  <% end %>
</div>

app/views/users/_profile.html.erb
<div class="profile white">
  <div class = "mypage profile-item center">
    <%= link_to user_path(id: current_user.id), class: 'font-gray' do %>
      <% if current_user.image.present? %>
        <%= image_tag current_user.image.url, class: 'show-image inline' %>
      <% else %>
        <%= image_tag 'man.png', class: 'show-image inline' %>
      <% end %>  
      <p class="inline"><%= current_user.name %></p>
    <% end %>
  </div>
  <div class ="message profile-item center">
    <%= link_to rooms_path, class: 'font-gray' do %>
      <%= image_tag "mail.png", class: 'inleine mail-icon' %>
      <p class="inline">メッセージ</p>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit-wrapper background-color">
  <div class="container">
    <div class="row">
      
      <div class="col-md-offset-3 col-md-6">
        <div class="edit-container white">
          <h2 class="text center">プロフィール編集</h2>
            <%= form_for @user do |f| %>
              <div class="form-container">
                <div class="center">
                  <% if @user.image.present? %>
                    <%= image_tag @user.image.url, class: 'user-image' %>
                  <% else %>
                    <%= image_tag 'man.png', class: 'user-image' %>
                  <% end %>  
                </div>  
                <div class="form-group">
                  <%= f.label :name, class: 'btn-text' %>
                  <%= f.text_field :name, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :gender, class: 'btn-text' %>
                  <%= f.select :gender, User.genders.keys, { }, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :age, class: 'btn-text' %>
                  <%= f.select :age, User.ages.keys, { }, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :prefecture, class: 'btn-text' %>
                  <%= f.select :prefecture, User.prefectures.keys, { }, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :description, class: 'btn-text' %>
                  <%= f.text_area :description, placeholder: '300字以内', rows: 7, class: 'form-control' %>
                </div>
                <div class="form-group">
                <%= f.label :artist, class: 'btn-text' %>
                  <%= f.text_area :artist, placeholder: '300字以内', rows: 7, class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :password, class: 'btn-text' %>
                  <%= f.password_field :password, value: @user.password, class: 'form-control' %>
                </div>
                
                <%= f.submit "編集", class: 'btn-block btn btn-default' %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/follow_list.html.erb
<div class="follow-list-wrapper background-color">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= render :partial => 'users/profile' %>
      </div>
      
      <div class="col-md-offset-1 col-md-6">
        <div class="follow-container white">
          <h2 class="text center"><%= @user.name %></h2>
          <div class="follow-btn center" >
            <p class="follow-member font-green btn">フォロー</p>
            <%= link_to "フォロワー", { controller: 'users', action: 'follower_list', user_id: @user.id}, class: 'follow-member font-black btn font-gray', method: :get %>
          </div>
          <div class="follow-user-container">
            <% if @user.all_following.present? %>
              <% @user.all_following.each do |user| %>
                <div class="follow-users center">
                  <%= link_to user_path(:id => user.id), class: 'follow-link' do %>
                    <% if user.image.present? %>
                      <%= image_tag user.image.url, class: 'user-image center' %>
                    <% else %>
                      <%= image_tag 'man.png', class: 'user-image center' %>
                    <% end %> 
                    <p class="user-name center font-gray"><%= user.name %></p>
                  <% end %>
                </div>
              <% end %>
            <% else %>
              <h4 class="no-follow center">フォローしている人はいません</h4>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/follower_list.html.erb
<div class="follow-list-wrapper background-color">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= render :partial => 'users/profile' %>
      </div>
      
      <div class="col-md-offset-1 col-md-6">
        <div class="follow-container white">
          <h2 class="text center"><%= @user.name %></h2>
          <div class="follow-btn center" >
            <%= link_to "フォロー", { controller: 'users', action: 'follow_list', user_id: @user.id }, class: 'follow-member btn font-gray', method: :get %>
            <p class="follow-member font-green btn">フォロワー</p>
          </div>
          <div class="follow-user-container">
            <% if @user.followers.present? %>
              <% @user.followers.each do |user| %>
                <div class="follow-users center">
                  <%= link_to user_path(:id => user.id), class: 'follow-link' do %>
                    <% if user.image.present? %>
                      <%= image_tag user.image.url, class: 'user-image center' %>
                    <% else %>
                      <%= image_tag 'man.png', class: 'user-image center' %>
                    <% end %>  
                    <p class="user-name center font-gray"><%= user.name %></p>
                  <% end %>
                </div>
              <% end %>
            <% else %>
              <h4 class="no-follow center">フォロワーはいません</h4>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="user-new-wrapper background-color">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <div class="new-container white">
          <h2 class="text center">新規登録</h2>
          <div class="new-form">
            <%= form_for @user do |f| %>
              <%= render 'layouts/error_messages', model: f.object %>
              <div class="form-group center">
                <% if @user.image? %>
                  <%= image_tag @user.image.url, class: 'user-image', id: :img_prev %>
                <% else %>
                  <%= image_tag "man.png", class: 'user-image', id: :img_prev %>
                <% end %>
              </div>
              <div class='center'>
                <label>
                  <p class='image-btn'>画像を選択</p>
                  <%= f.file_field :image, class: 'image-form', id: :user_img %>
                </label>
              </div>
              <div class="form-group">
                <%= f.label :name, class: 'btn-text' %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :email, class: 'btn-text' %>
                <%= f.text_field :email, class: 'form-control' %> 
              </div>
              <div class="form-group">
                <%= f.label :password, class: 'btn-text' %>
                <%= f.password_field :password, placeholder: '８文字以上、英数字を入れてください', class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password_confimation, class: 'btn-text' %>
                <%= f.password_field :password_confimation, class: 'form-control' %>
              </div>
              <%= f.submit "登録", class: 'btn-block btn login-btn' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-show-wrapper background-color">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <div class="show-container white">
          <h2 class="text-80 center"><%= @user.name %></h2>
          
          <div class="self-introduction">
            <div class="center">
              <% if @user.image.present? %>
                <%= image_tag @user.image.url, class: 'image' %>
              <% else %>
                <%= image_tag 'man.png', class: 'image' %>
              <% end %>  
            </div>
            
            <div class="follow-container center">
              <%= link_to "フォロー", { controller: 'users', action: 'follow_list', user_id: @user.id }, class: 'follow-member' %>
              <%= @user.follow_count %>
              <%= link_to "フォロワー", { controller: 'users', action: 'follower_list', user_id: @user.id}, class: 'follow-member' %>
              <%= @user.followers_count %>
            </div>
            <div class="follow center">
              <% if current_user.id == @user.id %>
                <%= link_to "編集", edit_user_path(current_user.id), class: 'edit-btn btn-hover btn btn-default' %>
              <% else %>
                <% if current_user.following? @user %>
                  <%= link_to "フォロー中", { controller: 'users', action: 'unfollow', user_id: @user.id }, class: 'follow-message btn-hover btn btn-info', method: :put %>
                  <%= render :partial => 'users/message' %>
                <% else %>
                  <%= link_to "フォローする", { controller: 'users', action: 'follow', user_id: @user.id }, class: 'follow-message btn-hover btn btn-default', method: :put %>
                  <%= render :partial => 'users/message' %>
                <% end %>
              <% end %>
            </div>
              
            <div class='item-container'>
              <div class="one-row">
                <div class="item">
                  <p class="birthplace mini-font"><%= @user.prefecture %></p>
                </div>
                <div class="item">
                  <p class="age mini-font"><%= @user.age %>歳</p>
                </div>
              </div>
              
              <div class="item item-border">
                <p class="description font">自己紹介</p>
                <p class="new-line"><%= @user.description %></p>
              </div>
              
              <div class="item item-border">
                <p class="artist font">好きなアーティスト</p>
                <p class="new-line"><%= @user.artist %></p>
              </div>
              
              <div class="item item-border">
                <p class="artist font">主催グループ</p>
                <% @user.communities. each do |community| %>
                  <%= link_to community_path(:id => community.id), class: 'font-gray' do %>
                    ・<%= community.title %>
                  <% end %>
                  <br>
                <% end %>
              </div>
              
              <div class="item item-border">
                <p class="community font">参加グループ</p>
                <% @user.join_communities. each do |community| %>
                  <%= link_to community_path(:id => community.community_id), class: 'community-name font-gray' do %>
                    ・<%= community.community.title %>
                  <% end %>
                  <br>
                <% end %>
              </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>