config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  
  resources :posts
  resources :join_communities, :only => [:show, :create, :destroy]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
  resources :communities do
    resources :join_communities, only: [:index]
  end
  
 resources :users
  

  
  
  get 'community/search'
  
  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  
  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
end

app/models/community.rb
class Community < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 300 }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :join_communities
  has_many :join_community_users, through: :join_communities, source: 'user'
  

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  def new
    @community = Community.new
  end
  
  def create
    @community = current_user.communities.new(community_params)
    if @community.save
      redirect_to communities_path, success: 'グループを作成しました'
    else
      render :new
    end
  end
  
  def index
    @communities = Community.all
    @q = Community.ransack(params[:q])
    @communities = @q.result(distinct: true)
  end
  
  def show
    @community = Community.find(params[:id])
    @post = Post.new
  end
  
  def destroy
    @community = Community.find(params[:id])
    @community.destroy
    redirect_to communities_path, danger: 'グループを削除しました'
  end
  
  def edit
    @community = Community.find(params[:id])
    if @community.user_id != current_user.id
      redirect_to root_path, danger: 'そのページにはいけません'
    end
  end
  
  def update
    @community = Community.find(params[:id])
      if @community.update(community_params)
        redirect_to community_path(params[:id]), success: '変更しました'
      else
        render :edit
      end
  end
  

  
  private
  def community_params
    params.require(:community).permit(:image, :title, :description)
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_admin.html.erb
<div class="admin-container">
  <div class="show-image-container center">
    <% if community.image.present? %>
      <%= image_tag community.image.url, class: 'show-image' %>
    <% else %>
      <%= image_tag 'livehouse.jpg', class: 'show-image' %>
    <% end %>
  </div>
  <div class="community-description">
    <div class="center">
      <p class="owner">管理者：</p>
       <%= link_to user_path(:id => community.user.id), class: 'owner font-gray' do %>
         <%= community.user.name %>
       <% end %>
    </div>
      <p class="title">説明</p>
      <p class="new-line"><%= community.description %></p>
  </div>
</div>

app/views/communities/edit.html.erb
<div class="community-edit-wrapper background-color">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= render :partial => 'users/profile' %>
      </div>
      
      <div class="col-md-8">
        <div class="new-container white">
          <h2 class="text center">グループ編集</h2>
          <div class="new-form">
            <div class="form-group">
              <div class='center'>
                <% if @community.image.present? %>
                  <%= image_tag community.image.url, class: 'community-image' %>
                <% else %>
                  <%= image_tag 'livehouse.jpg', class: 'community-image' %>
                <% end %>
              </div>
            </div>
            <%= form_for @community do |f| %>
              <%= render 'layouts/error_messages', model: f.object %>
              <div class="form-group">
                <%= f.label :title, class: 'btn-text' %>
                <%= f.text_field :title, class: 'form-control' %> 
              </div>
              <div class="form-group">
                <%= f.label :description, class: 'btn-text' %>
                <%= f.text_area :description, rows: 10,class: 'form-control' %>
              </div>
              
              <%= f.submit "編集", class: 'btn-block btn btn-default' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/communities/index.html.erb
<div class="community-index-wrapper background-color">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= render :partial => 'users/profile' %>
      </div>
     
      <div class="col-md-8">
        <div class="index-container white">
          <h2 class="text-80 center">グループ一覧</h2>
          <div class="search-container input-group">
            <%= search_form_for @q do |f| %>
              <%= f.text_field :title_cont, placeholder: 'キーワードを入力', class: 'search' %>
              <%= f.submit "検索", class: 'btn-hover btn btn-default' %>
            <% end %>
          </div>
          <div class="community-new">
            <%= link_to "グループ作成", new_community_path, class: 'new-btn btn btn-default btn-hover' %>
          </div>
          <div class="communities">
            <% @communities. each do |community| %>
              <div class="index">
                <% if community.image.present? %>
                  <%= image_tag community.image.url, class: 'index-image' %>
                <% else %>
                  <%= image_tag 'livehouse.jpg', class: 'index-image' %>
                <% end %>
                <div class="title-description new-line inline">
                  <p class="index-title"><%= community.title %></p>
                  <p class="member-count inline">参加メンバー</p>
                  <p class="join-member-count"><%= community.join_communities.count %>人</p>
                </div>
                <%= link_to "詳細", community_path(community.id) ,class: 'community-btn btn btn-default btn-hover' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
     
      <div class="col-md-2">
      </div>
    
  </div>
</div>

app/views/communities/new.html.erb
<div class="community-new-wrapper background-color">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= render :partial => 'users/profile' %>
      </div>
      <div class="col-md-8">
        <div class="new-container white">
          <h2 class="text center">グループ作成</h2>
          <div class="new-form">
            <%= form_for @community do |f| %>
              <%= render 'layouts/error_messages', model: f.object %>
              <div class="form-group center">
                <% if @community.image? %>
                  <%= image_tag @community.image.url, class: 'community-image', id: :img_prev %>
                <% else %>
                  <%= image_tag "livehouse.jpg", class: 'community-image', id: :img_prev %>
                <% end %>
              </div>
              <div class='center'>
                <label>
                  <p class='image-btn'>画像を選択</p>
                  <%= f.file_field :image, class: 'image-form', id: :user_img %>
                </label>
              </div>
              <div class="form-group">
                <%= f.label :title, class: 'btn-text' %>
                <%= f.text_field :title, class: 'form-control' %> 
              </div>
              <div class="form-group">
                <%= f.label :description, class: 'btn-text' %>
                <%= f.text_area :description, placeholder: "300字以内" , rows: 10, class: 'form-control' %>
              </div>
              
              <%= f.submit "作成", class: 'btn-hover btn btn-block btn-default' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/communities/show.html.erb
<div class="community-show-wrapper background-color">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= render :partial => 'users/profile' %>
      </div>

      <div class="col-md-7">
        <div class="show-container white">
          <h2 class="text-title center new-line"><%= @community.title %></h2>
          <div class="post center">
            <%= form_for @post,:url => {controller: "posts", action: "create" } do |f| %>
              <% if flash[:danger].present? %>
                <%= flash[:danger] %>
              <% end %>
              <%= f.text_field :content, placeholder: 'メッセージを入れてください', class: 'form-text-field' %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :community_id, :value => @community.id %>
              <%= f.submit '投稿', class: 'btn-hover btn btn-default' %>
            <% end %>
          </div>
          <div class="content-container">
            <% if @community.posts.present? %>
              <% @community.posts. each do |post| %>
                <div class="post-screen bottom-border">
                  <%= link_to user_path(:id => post.user_id) do %>
                    <% if post.user.image.present? %>
                      <%= image_tag post.user.image.url, class: 'user-image' %>
                    <% else %>
                      <%= image_tag 'man.png', class: 'user-image' %>
                    <% end %>  
                 <% end %>
                  <div class="user-content inline">
                    <%= link_to user_path(:id => post.user_id), class: 'user-name font-gray' do %>
                      <%= post.user.name %>
                    <% end %>
                    <p class="content new-line"><%= post.content %></p>
                    <%= l post.created_at %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <h4 class="no-message center">メッセージはありません</h4>
            <% end %>
          </div>
        </div>
      </div>
     
      <div class="col-md-3">
        <div class="show-container-right white">
         <%= render :partial => 'communities/admin', :locals => { community: @community } %>
         <div class="center">
           <% if current_user.id == @community.user_id %>
              <div class="center">
                <%= link_to "編集", edit_community_path(@community.id), class: 'owner-btn btn btn-default btn-hover' %>
                <%= link_to "削除", community_path(@community.id), class: 'owner-btn btn btn-default btn-hover', method: :delete %>
              </div>
            <% elsif !@community.join_community_users.include?(current_user) %>
              <%= link_to "参加", join_communities_path(:user_id => current_user.id, :community_id => params[:id]), class: 'join-btn btn btn-default btn-hover', method: :post %>
            <% else %>
              <%= link_to "参加中", join_community_path(:user_id => current_user.id, :community_id => params[:id]), class: 'join-btn btn btn-info btn-hover', method: :delete %>
            <% end %>
         </div>
          <p class="join-member title">参加メンバー</p>
          <p class="join-member-count"><%= @community.join_communities.count %>人</p>
          <div class="member">
            <% @community.join_communities. first(3). each do |community| %>
              <div class ="bottom-border">
                <%= link_to user_path(:id => community.user_id), class: 'user-name'  do %>
                  <% if community.user.image.present? %>
                      <%= image_tag community.user.image.url, class: 'join-user-image' %>
                    <% else %>
                      <%= image_tag 'man.png', class: 'join-user-image' %>
                    <% end %> 
                  <p class="font-gray inline"><%= community.user.name %></p>
                <% end %>
              </div>
            <% end %>
            <div class="plus-member">
              <% if @community.join_communities.count > 3 %>
                <%= link_to "さらに表示", community_join_communities_path(:community_id => params[:id]), class: 'btn font-gray center' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>