config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  
  resources :posts
  resources :join_communities, :only => [:show, :create, :destroy]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
  resources :communities do
    resources :join_communities, only: [:index]
  end
  
 resources :users
  

  
  
  get 'community/search'
  
  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  
  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 300 }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :join_communities
  has_many :join_community_users, through: :join_communities, source: 'user'
  

end

app/models/entry.rb
class Entry < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/join_community.rb
class JoinCommunity < ApplicationRecord
  
  belongs_to :user
  belongs_to :community
  
  
  
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true, length: { maximum: 100 }
  
  belongs_to :user, dependent: :destroy
  belongs_to :room, dependent: :destroy
  
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  
  validates :content, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
  validates :community_id, presence: true
  
  belongs_to :user
  belongs_to :community
  
end

app/models/room.rb
class Room < ApplicationRecord
 
  
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: {maximum: 15}
  VALID_PASSWORED_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  validates :password, presence: true,  uniqueness: true, length: {minimum: 8, maximum: 32 }, format: {with: VALID_PASSWORED_REGEX}
  validates :artist, length: { maximum: 300 }
  validates :description, length: { maximum: 300 }

  mount_uploader :image, ImageUploader
  
  has_secure_password
  
  has_many :communities, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :join_communities
  has_many :join_community_communities, through: :communities, source: 'community'
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  acts_as_followable
  acts_as_follower
  
  enum prefecture: {
   北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
   茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
   新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
   岐阜県:21,静岡県:22,愛知県:23,三重県:24,
   滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
   鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
   徳島県:36,香川県:37,愛媛県:38,高知県:39,
   福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  
  enum age: {
    １:1,２:2,３:3,４:4,５:5,６:6,７:7,８:8,９:9,１０:10,
    １１:11,１２:12,１３:13,１４:14,１５:15,１６:16,１７:17,１８:18,１９:19,２０:20,
    ２１:21,２２:22,２３:23,２４:24,２５:25,２６:26,２７:27,２８:28,２９:29,３０:30,
    ３１:31,３２:32,３３:33,３４:34,３５:35,３６:36,３７:37,３８:38,３９:39,４０:40,
    ４１:41,４２:42,４３:43,４４:44,４５:45,４６:46,４７:47,４８:48,４９:49,５０:50,
    ５１:51,５２:52,５３:53,５４:54,５５:55,５６:56,５７:57,５８:58,５９:59,６０:60,
    ６１:61,６２:62,６３:63,６４:64,６５:65,６６:66,６７:67,６８:68,６９:69,７０:70,
    ７１:71,７２:72,７３:73,７４:74,７５:75,７６:76,７７:77,７８:78,７９:79,８０:80,
    ８１:81,８２:82,８３:83,８４:84,８５:85,８６:86,８７:87,８８:88,８９:89,９０:90,
    ９１:91,９２:92,９３:93,９４:94,９５:95,９６:96,９７:97,９８:98,９９:99,１００:100
  }
  
  enum gender: {
    男性:1,女性:2
  }
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def show
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to controller: 'communities', action: 'show', id: @post.community_id
    else
      
      #redirect_to :back ,flash: {danger: "入力されていない項目があります"}
      redirect_to controller: 'communities', action: 'show', id: @post.community_id, flash: {danger: "入力されていない項目があります"}
    end
  end
  
  
  
  private
  def post_params
    params.require(:post).permit(:user_id, :community_id, :content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  
  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry). permit(:room_id, :user_id). merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end
  
  def show  
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
     # @entryuser = Entry.where(room_id: @room.id).where.not(user_id: current_user.id).first
      @entryuser = Entry.find_by("room_id = ? and user_id != ?", @room.id, current_user.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  def index
    @entry = Entry.where(user_id: current_user.id)
    entryuser = []
    @entry.each do |entry|
      entryuser << entry.room_id
    end
    @entryuser = Entry.where(room_id: entryuser).where.not(user_id: current_user.id)
   
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert-warning">
     <ul>
       <% model.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-fixed-top bottom-border">
      <div class="container" >
        
        <div class="navbar-left">
          <%= link_to "M-Search", root_path, class: 'link' %>
        </div>
        
        <div class="navbar-right">
          <ul>
           <% if logged_in? %>
              <li>
                <%= link_to "マイページ", user_path(id: current_user.id), class: 'link' %>
              </li>
              <li>
                <%= link_to "グループ", communities_path, class: 'link' %>
              </li>
              <li>
                <%= link_to "ログアウト", logout_path, class: 'link', method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "新規登録", new_user_path, class: 'link' %>
              </li>
              <li>
                <%= link_to "ログイン", login_path, class: 'link' %>
              </li>
            <% end %>
          </ul>
        </div>
      
      </div>
    </nav>
     
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
    
    <script type="text/javascript">
      $(function() {
       function readURL(input) {
         if (input.files && input.files[0]) {
           var reader = new FileReader();
           reader.onload = function (e) {
       $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
       }
       $("#user_img").change(function(){
         readURL(this);
       });
      });
    </script>
    
    <footer class="footer center">
      <div class="footer-center">
        <p>M-Search</p>
      </div>
    </footer>
  
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-wrapper">
  
  <div class="main-container background-image">
    <div class="container">
      <div class="top-container">
        <h1 class="title">M-Search</h1>
        <h4 class="title">ライブ・フェス同行者を探せるサービス</h4>
      </div>
    </div>
  </div>
  
  <div class="row-container">
    <div class="container">
      <div class="row">
        <div class="row-container-left col-md-offset-2 col-md-4">
          <div class="image center">
            <%= image_tag 'team.png', class:'team-image' %>
          </div>
          <div class="function">
            <h2 class="function-title center">グループ</h2>
            <h5 class="function-description center">グループに参加することで友達の輪を広げよう</h5>
          </div>
        </div>
        <div class="row-container-right col-md-4"> 
          <div class="image center">
            <%= image_tag 'mail2.png', class: 'mail-image' %>
          </div>
          <div class="function">
            <h2 class="function-title center">DM機能</h2>
            <h5 class="function-description center">特定の相手と個別にやりとりができる</h5>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>